---
# Kafka Headless Service
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: NAMESPACE_NAME
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: internal
    - port: 9093
      name: controller
  selector:
    app: kafka
---
# Kafka Client Service
apiVersion: v1
kind: Service
metadata:
  name: kafka-client
  namespace: NAMESPACE_NAME
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      name: client
  selector:
    app: kafka
