---
# StorageClass với 1 replica (single replica) để tiết kiệm storage
# RabbitMQ cluster vẫn HA nhờ 3 nodes, nhưng storage không replicate
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-single-replica
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
