---
# ServiceAccount cho RabbitMQ pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: NAMESPACE_NAME
---
# Role - Quyền để RabbitMQ tự discover các pods khác trong cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbitmq
  namespace: NAMESPACE_NAME
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
# RoleBinding - Gắn Role vào ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq
  namespace: NAMESPACE_NAME
subjects:
  - kind: ServiceAccount
    name: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq
