---
# RabbitMQ StatefulSet - 3 nodes cluster
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: NAMESPACE_NAME
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq-headless
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: rabbitmq
      terminationGracePeriodSeconds: 30
      
      # Pod Anti-Affinity - Cố gắng chia pods ra các nodes khác nhau
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rabbitmq
                topologyKey: kubernetes.io/hostname
      
      initContainers:
        - name: setup-config
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              set -ex
              # Copy config files
              cp /configmap/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
              cp /configmap/enabled_plugins /etc/rabbitmq/enabled_plugins
              
              # Set permissions
              chmod 644 /etc/rabbitmq/rabbitmq.conf
              chmod 644 /etc/rabbitmq/enabled_plugins
          volumeMounts:
            - name: config
              mountPath: /configmap
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
      
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management-alpine
          imagePullPolicy: IfNotPresent
          
          env:
            # Credentials từ Secret
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-erlang-cookie
            
            # Cluster configuration
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RABBITMQ_NODENAME
              value: "rabbit@$(POD_NAME).rabbitmq-headless.$(POD_NAMESPACE).svc.cluster.local"
            - name: K8S_SERVICE_NAME
              value: "rabbitmq-headless"
            - name: K8S_HOSTNAME_SUFFIX
              value: ".rabbitmq-headless.$(POD_NAMESPACE).svc.cluster.local"
          
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
            - name: prometheus
              containerPort: 15692
              protocol: TCP
            - name: epmd
              containerPort: 4369
              protocol: TCP
            - name: dist
              containerPort: 25672
              protocol: TCP
          
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
          
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - check_running
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
      
      volumes:
        - name: config
          configMap:
            name: rabbitmq-config
        - name: rabbitmq-config
          emptyDir: {}
  
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: rabbitmq
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn-single-replica
        resources:
          requests:
            storage: 3Gi
