---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: automation
type: Opaque
stringData:
  DB_PASSWORD: "21042004"
  N8N_ENCRYPTION_KEY: "glXgNqD7NKplHYDR8pbr+CuuoQW2gPHt7+K5iYtoFrk="
