---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: automation
  labels:
    app: n8n
spec:
  type: LoadBalancer
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: http
  selector:
    app: n8n
