---
# MetalLB IP Address Pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: infrastructure-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.16.21.200-172.16.21.250  # Range IP cho LoadBalancer services
---
# L2 Advertisement
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: infrastructure-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - infrastructure-pool
